app:
  short-url-base: ${PUBLIC_SHORT_URL_BASE:http://localhost:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/url_shortener}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  cloud:
    consul:
      host: localhost
      port: 8500
